# Generated by Django 2.1.3 on 2018-11-25 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('date', models.DateField(default=datetime.datetime(2018, 11, 25, 17, 54, 8, 52734, tzinfo=utc), null=True)),
                ('like_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='password', max_length=15)),
                ('last_login', models.DateField(default='2018-01-01', null=True)),
                ('last_ipaddress', models.CharField(max_length=20, null=True)),
                ('message_list', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='msg_board.Message')),
            ],
        ),
    ]
