# Generated by Django 2.1.3 on 2018-11-23 13:49

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('date', models.DateField()),
                ('like_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(default='password', max_length=15)),
                ('last_login', models.DateField(default='2018-01-01', null=True)),
                ('last_ipaddress', models.CharField(blank=True, max_length=20)),
                ('message_list', djongo.models.fields.ArrayReferenceField(default='', null=True, on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='msg_board.Message')),
            ],
        ),
    ]
