# Generated by Django 2.1.3 on 2018-11-25 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('msg_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 18, 42, 2, 931403, tzinfo=utc), null=True),
        ),
    ]
