# Generated by Django 2.1.3 on 2018-11-25 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('msg_board', '0002_auto_20181125_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 19, 5, 0, 25646, tzinfo=utc), null=True),
        ),
    ]
